import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {Game,LEVELS,OFFICES,REVIEWS,CATCH_Y,normalizeSave} from '../../static/play/eat-the-boss/engine.js';
const quietGame=(level=0)=>{const g=new Game(()=>.6);g.start(level);g.spawnClock=99999;return g;};
function dropAtMouth(g,type='poop',x=g.x){g.drops.push({type,x,y:g.catchY-1,vx:0,vy:200,phase:0,rotation:0});g.update(.02);}
test('normal floors promote only after the quota and streak are met',()=>{let points=0;for(let level=0;level<19;level++){if(REVIEWS[level])continue;const g=quietGame(level);g.score=points;for(let n=0;n<LEVELS[level].quota;n++)dropAtMouth(g);assert.equal(g.state,'promoted');assert.equal(g.level,level);assert.ok(g.score>points);assert.equal(g.events.filter(e=>e.type==='promoted').length,1);points=g.score;}assert.equal(LEVELS.length,20);assert.equal(new Set(LEVELS.map(l=>l.title)).size,20);});
test('gold fills three quota, money restores health, hazards cost a heart',()=>{const g=quietGame(6);dropAtMouth(g,'gold');assert.equal(g.quota,3);dropAtMouth(g,'file');assert.equal(g.lives,2);dropAtMouth(g,'money');assert.equal(g.lives,3);assert.equal(g.quota,3);});
test('missed crap falls out of play and ends the run after three separate misses',()=>{const g=quietGame();for(let i=0;i<3;i++){g.invincible=0;g.drops.push({type:'poop',x:20,y:679,vy:200,vx:0});g.update(.02);}assert.equal(g.state,'gameover');assert.equal(g.lives,0);assert.equal(g.drops.length,0);});
test('pause freezes movement, hazards, and spawn timer',()=>{const g=quietGame();g.state='paused';g.drops.push({x:200,y:300,vy:200,vx:0,type:'poop'});g.update(.04,{direction:1,targetX:500});assert.equal(g.x,270);assert.equal(g.drops[0].y,300);assert.equal(g.time,0);});
test('touch targets and keyboard movement remain inside the playfield',()=>{const g=quietGame();for(let i=0;i<80;i++)g.update(.02,{targetX:10000});assert.equal(g.x,510);for(let i=0;i<80;i++)g.update(.02,{direction:-1});assert.equal(g.x,30);});
test('saved state tolerates corrupted values and keeps valid local progress',()=>{assert.deepEqual(normalizeSave(null),{level:0,score:0,best:0,won:false});assert.deepEqual(normalizeSave({level:500,score:-3,best:Infinity,won:'yes'}),{level:19,score:0,best:0,won:false});assert.deepEqual(normalizeSave({level:8,score:440,best:2000,won:false}),{level:8,score:440,best:2000,won:false});});
test('standing still no longer clears a floor and all 20 floors have office artwork',()=>{for(let level=0;level<20;level++){const g=new Game(()=>.6);g.start(level);for(let frame=0;frame<60*60&&g.state==='playing';frame++)g.update(1/60);assert.equal(g.state,'gameover',`floor ${level+1}`);const office=OFFICES[LEVELS[level].office];assert.ok(level>=office.first&&level<=office.last);assert.ok(fs.existsSync(path.join('static/play/eat-the-boss',office.asset)));}});
test('concurrent hazard and catch are separated into distinct arrival windows',()=>{const g=quietGame(15);g.drops.push({type:'poop',x:270,y:104,vy:300,vx:0});const file={type:'file',x:270,y:104,vy:300,vx:0};g.spaceHazard(file);assert.ok(Math.abs((CATCH_Y-104)/file.vy-(CATCH_Y-104)/300)>=.22);});
test('local HTML, module imports, and image references resolve',()=>{const root=path.resolve('static/play/eat-the-boss');const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){const ref=m[1];if(ref==='./'||ref.startsWith('https:'))continue;assert.ok(fs.existsSync(path.join(root,ref)),ref);}const js=fs.readFileSync(path.join(root,'game.js'),'utf8');for(const m of js.matchAll(/(?:from |\.src=)'([^']+)'/g)){assert.ok(fs.existsSync(path.join(root,m[1])),m[1]);}});
